[package]
name = "aes-key-wrap"
description = "Pure Rust implementation of Advanced Encryption Standard (AES) Key Wrap Algorithm (RFC-3394)"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
repository = "https://github.com/pr0n00gler/aes-key-wrap"
license = "MIT"

[dependencies]
aes = { version = "0.9.1", features = ["zeroize"] }
subtle = "2.6.1"
zeroize = "1.9.0"

[dev-dependencies]
aes-kw = { version = "0.3.1", default-features = false }
proptest = { version = "1.11.0", default-features = false, features = ["std"] }
wycheproof = { version = "0.6.0", default-features = false, features = ["keywrap"] }
